### ISSUE TITLE
rodauth.rails_account is not properly refreshed after become_account in tests

### ISSUE THREAD

**Issue by pboling** [janko/rodauth-rails#332] opened 2024-11-12 10:09 UTC
1.15.0 release said:

> The model instance returned by `rodauth.rails_account` is now refreshed when `rodauth.account` changes. This fixes integration with [rodauth-become_account](https://github.com/adam12/rodauth-become_account) gem.

My issue is I'm trying to write a system test that first verifies an account, and then utilizes `become_account` to become that account, which means my ActiveRecord queries are running inside a giant transaction, and my Sequel queries can't see the changes.

Note: `Vc::Account` is my rails account model.

before running:
```
          rodauth.become_account(account)
```
I have the following state:
```
(byebug) rodauth.rails_account
nil
(byebug) account
#<Vc::Account id: 5, status: "verified", email: "virtualadmin@virtualhospital.com", password_hash: "$2a$04$QI3FMHP9q9LxZU2fTz9SV.EuAQ5hxnQHu.89.5iI6QU...", organization_id: 2, user_id: 2>
```

After running `become_account` I have the following state:
```
(byebug) rodauth.rails_account
#<Vc::Account id: 5, status: "unverified", email: "virtualadmin@virtualhospital.com", password_hash: "$2a$04$QI3FMHP9q9LxZU2fTz9SV.EuAQ5hxnQHu.89.5iI6QU...", organization_id: 2, user_id: 2>
(byebug) Vc::Account.find(5)
#<Vc::Account id: 5, status: "verified", email: "virtualadmin@virtualhospital.com", password_hash: "$2a$04$QI3FMHP9q9LxZU2fTz9SV.EuAQ5hxnQHu.89.5iI6QU...", organization_id: 2, user_id: 2>
```

Notice that the `status` is `unverified` in the `rails_account` copy.  I believe this is due to the verified state change being invisible outside the transaction, which is only being accessed when queried via ActiveRecord, not Sequel.

Then later, when the view is being rendered, I get this nonsensical state:
```
(byebug) rodauth.logged_in?
true
(byebug) rodauth.rails_account
nil
```

I'm not sure how to properly test this... and maybe there isn't a good way.  Also, the `rodauth.rails_account` seems to be refreshed twice, and both times what it becomes is not what I want.  First the stale unverified account, and then `nil`.

**Comment by janko** [comment] 2024-11-16 21:46
Thanks for the report. I will need a minimal Rails app that reproduces the issue to debug this, as I'm missing some context here.

FWIW I don't think the issue here is Sequel queries not seeing changes made by Active Record, because Sequel is using Active Record's database connection, so they should all be within the same transaction.

**Comment by pboling** [comment] 2024-11-26 22:44
I've been swamped, but I am going to circle back around to this within weeks I expect.

**Comment by janko** [comment] 2024-12-16 19:51
OK, I will close this until I get more context.

For now it doesn't appear that it can be solved, because `rails_account` is a copy of `account`, and the `rodauth-become_account` compatibility fix busts the cache when account ID changes, but I think it lead to surprising behavior if the account model instance is rebuild on any account value change (assuming there even is a reasonable implementation).

**Closed by janko** 2024-12-16 19:51 UTC
