### ISSUE TITLE
HTML not rendering in production vs development environment.

### ISSUE THREAD

**Issue by Swalden** [janko/rodauth-rails#182] opened 2022-12-09 05:49 UTC
Hi,

I'm having issues with html not being rendered in production vs my development environment. I'm really lost  as to the cause here. I've attached two photos. The one with more HTML under the login button as well as the text saying Footer (which is actually in the layout HTML file.) is the development environment.

Only screens using Rodauth are dropping the HTML in production. I'm really unsure why.

<img width="1336" alt="CleanShot 2022-12-09 at 16 47 07@2x" src="https://user-images.githubusercontent.com/4156182/206633334-c13d95de-6844-40f0-bf7a-b2a542cc155b.png">
<img width="1529" alt="CleanShot 2022-12-09 at 16 46 51@2x" src="https://user-images.githubusercontent.com/4156182/206633343-9fe69a0d-40b4-4a69-a11d-4e0eda9322fa.png">

**Comment by janko** [comment] 2022-12-09 09:02
The [official Rails demo](https://github.com/janko/rodauth-demo-rails) is working just fine in production environment, so I think you have something different in your code that's causing issues. If you want me to help you debug, I would need you to reproduce the issue in a fresh Rails application.

It's unlikely this is a bug in rodauth-rails, so I'm closing the issue, and will reopen if it indeed turns out to be a bug.

**Closed by janko** 2022-12-09 09:02 UTC
