### ISSUE TITLE
How would you authentication a new connection for ActionCable via the session cookie?

### ISSUE THREAD

**Issue by kyle-rader** [janko/rodauth-rails#151] opened 2022-09-05 16:13 UTC
I'm starting to use ActionCable and have a connection class that looks like the following. What's the best way to authenticate this connection using the existing session?
```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      # Question: How to find current user from session?
      if verified_user = Account.find_by(id: cookies.encrypted[??]) # or Some Rodauth::Auth::auth_method?
        verified_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

**Comment by janko** [comment] 2022-09-05 16:52
If Action Cable connections have access to request env, you should be able to do:

```rb
verified_user = env["rodauth"].rails_account
```

For secondary configurations, e.g. `:admin`, you'd call `env["rodauth.admin"].

It might be worth adding similar helpers for controllers to Action Cable connections in rodauth-rails 🤔

**Comment by janko** [comment] 2022-09-05 16:54
I'm going to close this, as it's not a bug report. Please ask usage questions in discussions channel 🙂

**Closed** 2022-09-05 16:55 UTC
