### ISSUE TITLE
Black QR-Code during OTP setup

### ISSUE THREAD

**Issue by gismoog** [janko/rodauth-rails#169] opened 2022-11-06 12:04 UTC
I'am not able to display a QR-Code do complete OTP setup because I only get a fully black QR-Code.

When I remove

`<rect width="456" height="456" x="0" y="0" fill="##fff"></rect>`

in the HTML-Code Rodauth generated everything works fine.

rqrcode (2.1.2)
rqrcode_core (1.2.0)
rodauth (2.26.0)
rodauth-i18n (0.5.1)
rodauth-model (0.2.1)
rodauth-rails (1.6.2)

`<%= rodauth.otp_qr_code.html_safe %>`:

<img width="421" alt="Bildschirm­foto 2022-11-06 um 12 59 53" src="https://user-images.githubusercontent.com/78080735/200169458-df67bb1e-d271-4c98-8090-f8a68427d282.png">

**Comment by gismoog** [comment] 2022-11-06 12:32
Ups,

I just downgraded the rodauth gem from 2.26.0 to 2.25.0 and everything is working again.

The changelog.md of rodauth contains the following line:

* Use white background instead of transparent background for QR code in otp feature (jeremyevans) (#256)

I think this will cause the problem.

BTW: I use tailwind.css

**Comment by janko** [comment] 2022-11-06 12:46
Interesting, I believe this change in Rodauth was intended precisely to prevent this from happening when using dark mode with Tailwind CSS. So, I would expect the QR code to be completely black on versions 2.25 and below (because it uses a transparent background), and to appear normal in versions 2.26 and above.

**Comment by janko** [comment] 2022-11-07 23:31
You're right, this really was a regression in the latest Rodauth version. I opened https://github.com/jeremyevans/rodauth/pull/279 to fix it. I'm going to close this one, since it's not an issue with rodauth-rails.

**Closed by janko** 2022-11-07 23:31 UTC
